# Julia:  Condicionais, repetições e funções 
 - Built-in function input
 - Condicionais 
 - Repetição: for 
 - Repetição: While 
 - Funções 
 - Função Fatorial 
 - Escopo 
 - File I/O

## Built-in function input


Antes de estudar condicionais, veremos alguns exemplos de built-in functions.

In [6]:
print("Qual  é seu nome: ")
name = readline()
print("Qual é sua idade")
idade = readline()
println("idade: ",idade)
print("\n\n")

Qual  é seu nome: 

stdin>  hector 


Qual é sua idade

stdin>  41


idade: 41




In [3]:
typeof(name)

String

In [7]:
typeof(idade)

String

In [10]:
idade= parse(Float64,idade)

41.0

In [11]:
typeof(idade)

Float64

## Condicionais 
Condicionais servem para controlar o fluxo do programa. Em outras palavras, partes do código só serão executadas se determinada condição, de valor booleano, for verdadeira. Vejamos um exemplo

In [15]:
expr = true
if expr 
    println("Ola ! ")
end

Ola ! 


In [16]:
expr1 = true
expr2 = false
if expr1 
    println("Expr 1 é verdadeira ! ")
    println("Expr 2 é false ! ")
end
if expr2 
    println("Expr 1  não será impressa ! ")
    println("Expr 2   não será impresa! ")
end


Expr 1 é verdadeira ! 
Expr 2 é false ! 


In [18]:
expr1 = true
expr2 = false
if expr1 
    println("Expr 1 é verdadeira ! ")
    println("Expr será impresa ! ")
elseif expr2 
    println("Expr 1  não será impressa ! ")
    println("Expr 2   não será impresa! ")
end

Expr 1 é verdadeira ! 
Expr será impresa ! 


## Aplicação 

Um excelente site para praticar seus conhecimentos em Python é o Uri Online. Durante os tutoriais daremos vários exemplos baseados nesse site.

Na seção de iniciantes, o problema 1044 pede para você verificar se dois números, passados por um usuário, são múltiplos ou não. O usuário entra com dois números inteiros, numa única linha e separados por um único espaço

In [23]:
entrada = readline() 

stdin>  4 5


"4 5"

In [24]:
snum = split(entrada," ")

2-element Vector{SubString{String}}:
 "4"
 "5"

In [27]:
snum[1]
snum[2]

"5"

In [29]:
num = [parse(Int64,snum[1]), parse(Int64,snum[2])] 

2-element Vector{Int64}:
 4
 5

In [31]:
expr1 = (mod(num[2],num[1]) == 0)
expr2 = (mod(num[1],num[2]) == 0)


false

In [33]:
if expr1
    println("São multiplos") 
elseif expr2
    println("São multiplos") 
else 
    println("Não são multiplos") 
end

Não são multiplos


## Repitição FOR
Algumas vezes, uma mesma sequência de comandos deve ser executada diversas vezes. Para fazer isso utilizamos estruturas de repetição. Observe o código:

In [37]:
x = 1 
x = x + 2
x = x + 2 
x = x + 2 
x = x + 2 
println(x)

9


Como as linha 2, 3, 4 e 5, são repetidas, podemos utilizar um estrutura de repetição. O for é a keyword utilizada para tal. Vejamos:

In [38]:
x = 1 
for i in [1,2,3,4]
    x = x + 2     
end
println(x)

9


In [41]:
x = 1 
for i in [1,2,3,4]
    x = x + 2     
    println("i= ",i,", x= ",x)
end
println(x)

i= 1, x= 3
i= 2, x= 5
i= 3, x= 7
i= 4, x= 9
9


## range
O comum é utilizar a função range. Vejamos alguns exemplos de uso da função:

In [49]:
x = 1:2:11

1:2:11

In [50]:
typeof(x)

StepRange{Int64, Int64}

In [51]:
collect(x)

6-element Vector{Int64}:
  1
  3
  5
  7
  9
 11

In [52]:
collect(4:10)

7-element Vector{Int64}:
  4
  5
  6
  7
  8
  9
 10

In [53]:
x = 1 
for i in 1:1000000
    x = x + 2
end
println(x)

2000001


##  Practicando 
O problema número 1067 da seção iniciante pede para imprimir os números ímpares de 1 até X, inclusive X (se for o caso), com X sendo um número inteiro de 1 a 1000 recebido como entrada de um usuário.

In [61]:
entrada = readline() 
num = parse(Int64,entrada) 
typeof(num)
for i in 1:num
    expr = (mod(i,2)==1)
    if expr
        println(i)
    end
end


stdin>  7


1
3
5
7


## Repitição: while 

In [62]:
x = 1 
x = x + 2
x = x + 2 
x = x + 2 
x = x + 2 
println(x)

9


In [63]:
x = 1; i = 2
expr = (i<6)
while expr
    x = x + i
    i = i + 1
    expr =(i<6)
end
println("x= ",x)


x= 15


In [66]:
entrada = readline() 
num = parse(Int64,entrada) 
i = 1
expr =  (i<=num)
while expr
    expr1 = (mod(i,2)==1)
    if expr1
        println(i)
    end
    i = i + 1 
    expr =  (i<=num)
end


stdin>  7


1
3
5
7


## Funções 
Funções são utilizadas para agrupar uma série de comandos na intenção de reutilizálos. Por exemplo, se você quer saber se três variáveis X, Y e Z têm valores inteiros pares, uma opção seria:

In [68]:
X = 7
if mod(X,2) == 0
    println("Par")
else
    print("Impar")
end

Y = 2 
if mod(Y,2) == 0
    print("Par")
else
    print("Impar")
end

Z = 42
if mod(Z,2) == 0
    print("Par")
else
    print("Impar")
end

ImparParPar

In [72]:
function isPar(var)
    if mod(var,2)==0
        println("Par")
    else
        println("impar")
    end
end


isPar (generic function with 1 method)

In [73]:
isPar(X)
isPar(Y)
isPar(Z)

impar
Par
Par


In [79]:
function digaOla()
    println("Ola")
end


digaOla (generic function with 1 method)

In [82]:
digaOla()

Ola


Uma função pode ter 2 ou mais parâmetros:

In [83]:
function max_numbers(x,y)
    if x>y
        println(x)
    else
        println(y)
    end
end

max_numbers (generic function with 1 method)

In [84]:
max_numbers(10,3)

10


Uma função pode ter parâmetros não obrigatórios ou default.

In [87]:
function seApresente(nome, pais="Brasil")
    println("eu sou ", nome," do ",pais)
end

seApresente (generic function with 2 methods)

In [88]:
seApresente("Hector")

eu sou Hector do Brasil


In [89]:
seApresente("Hector","Bolivia")

eu sou Hector do Bolivia


## Return 

In [93]:
function seApresente(nome, pais="Brasil")    
    return println("eu sou ", nome," do ",pais)
end

seApresente (generic function with 2 methods)

##  Funções com varios Parametros 

In [103]:
"""
crazySum(a,b,c,d,e,f)

computte  the sum 

if `d,e,f` is unspecified, is used the default value 
# Examples
```Julia-repl
julia> crazySum(1,2,3)
1 
```
"""
function crazySum(a,b,c,d=1,e=2,f=3)
    #=
    dskjdskds 
    =#
    print( a + b + c + d + 2*e + 3*f )
end

crazySum

In [104]:
crazySum(10,20,30)

74

In [105]:
?crazySum

search: crazySum



crazySum(a,b,c,d,e,f)

computte  the sum 

if `d,e,f` is unspecified, is used the default value 

# Examples

```Julia-repl
julia> crazySum(1,2,3)
1 
```


### Função matemática 

In [101]:
f(x,y) = x+y

f (generic function with 1 method)

In [102]:
∑(x,y) = x+y

∑ (generic function with 1 method)

## Função Fatorial 
Esta seção tem o objetivo de praticar quase tudo visto nesse tutorial. Para isso criaremos uma função, chamada fatorial, que retorna o fatorial de um número n dado como parâmetro de entrada da função.

In [106]:
function fatorial(n)
    if n == 0
        return 1 
    elseif n==1
        return 1 
    else
        resultado = 1 
        for i in 1:n
            resultado=resultado*i
        end    
        return resultado        
    end        
end    
    

fatorial (generic function with 1 method)

In [108]:
fatorial(0)

1

In [109]:
fatorial(5)

120

### Recursiva

In [112]:
function fatorial(n)
    if n == 0
        return 1 
    elseif n==1
        return 1 
    else
       n*fatorial(n-1)
    end        
end    


fatorial (generic function with 1 method)

In [114]:
fatorial(5)

120