# 💻 Introdução a  Julia 
- Variáveis  e atribuição de valores 
- Tipos de variáveis 
- Inteiros 
- Numeros flutuantes 
- Booleanos 
- String 
- listas 
- tuplas 
- Dicionários 
- Conjuntos 
- Mudando o tipo de variaveis 

## 1 Variável    e atribuição de valores 
Variáveis são espaços na memória do seu computador. Para atribuir algum valor a uma variável usa-se a seguinte sintaxe:

my_float = 3.0 

(variavel) (sinal de atrbuição )(valor)


In [1]:
my_float = 3.0  

3.0

In [2]:
😄 = 23 

23

In [3]:
😈 = -7

-7

In [4]:
😏 = 😄 + 😈

16

In [5]:
typeof(😏)

Int64

## 💯 Tipos de  variáveis 

In [6]:
x =  3.0 

3.0

In [7]:
typeof(x)

Float64

In [8]:
x = "tres"

"tres"

In [9]:
typeof(x)

String

In [10]:
x = true 

true

In [11]:
typeof(x)

Bool

In [12]:
x = [3,4,5]


3-element Vector{Int64}:
 3
 4
 5

In [13]:
typeof(x)

Vector{Int64} (alias for Array{Int64, 1})

In [14]:
🍌= 7

7

In [15]:
typeof(🍌)

Int64

In [16]:
😄 = 10 

10

In [17]:
😄 + 🍌

17

## Inteiros 
 

In [18]:
x = 3 

3

In [19]:
typeof(x)

Int64

In [20]:
y =5 

5

In [21]:
z = x - y 

-2

In [22]:
typeof(z)

Int64

In [23]:
x^2

9

x/y

In [24]:
x//y

3//5

## Operações lógicas com inteiros 

In [25]:
# relação de ordem 
x>y

false

In [26]:
x>=y

false

In [27]:
x==y

false

## Operações lógicas com variaveis booleanas 

In [28]:
x =  true; y= false;  

In [29]:
x && y

false

In [30]:
x || y

true

In [31]:
~ x

false

In [32]:
x == y 

false

## Aplicação  (checando a validade das leis de morgan)

In [33]:
x =  true; y = true;
!( x && y) == (! x ||  ! y)



true

In [34]:
x=  false; y = true;
!( x && y) == (! x ||  ! y) 

true

In [35]:
x= false ; y = false;
!( x && y) == (! x ||  ! y)

true

# Slicing String 

In [36]:
name = "Skywalker"

"Skywalker"

In [37]:
name[1]

'S': ASCII/Unicode U+0053 (category Lu: Letter, uppercase)

In [38]:
name[end] ##   in python work  name[-1]

'r': ASCII/Unicode U+0072 (category Ll: Letter, lowercase)

In [39]:
name[1:3]  ## anoter diference  with python 

"Sky"

In [40]:
name[end-2:end]

"ker"

In [41]:
name[begin:2:end]

"Syakr"

In [42]:
reverse(name) 

"reklawykS"

In [43]:
length(name)

9

# Arrays

In [44]:
lista=  Array{Any,1}(undef,4)

4-element Vector{Any}:
 #undef
 #undef
 #undef
 #undef

In [45]:
lista[1]= "a"

"a"

In [46]:
lista[2]= 2

2

In [47]:
lista[3] = "fchect"

"fchect"

In [48]:
lista[4] = 2.3

2.3

In [49]:
lista

4-element Vector{Any}:
  "a"
 2
  "fchect"
 2.3

In [50]:
ligth = Array{String}(undef,2)

2-element Vector{String}:
 #undef
 #undef

In [51]:
greek_letters = ["Eta","Mu","Psi","Tau","Phi"]

5-element Vector{String}:
 "Eta"
 "Mu"
 "Psi"
 "Tau"
 "Phi"

In [52]:
greek_letters[1]

"Eta"

In [53]:
greek_letters[end]

"Phi"

## Tuples 

In [54]:
tupl = (2,3,4,5)

(2, 3, 4, 5)

In [55]:
tupl = ((2,3,4,5),(2,3,5,6))

((2, 3, 4, 5), (2, 3, 5, 6))

In [56]:
tupl[1]

(2, 3, 4, 5)

In [57]:
tupl[1][1]

2

In [58]:
# tupla com string floats, bolean, inteiros etc 
tupl = (4,1.4,"quatro",'3',false,[4,"um"])

(4, 1.4, "quatro", '3', false, Any[4, "um"])

In [59]:
reverse(tupl)

(Any[4, "um"], false, '3', "quatro", 1.4, 4)

In [60]:
length(tupl)

6

In [61]:
map(typeof,tupl)

(Int64, Float64, String, Char, Bool, Vector{Any})

In [62]:
isempty(tupl)

false

In [63]:
tupl

(4, 1.4, "quatro", '3', false, Any[4, "um"])

In [64]:
tupl[1:3]

(4, 1.4, "quatro")

## Dicionários 

In [65]:
numbers = Dict(
    1=>"um", 
    5=>"cinco",
    18=>"dezeoito",
    20=>"vinte" )

Dict{Int64, String} with 4 entries:
  5  => "cinco"
  20 => "vinte"
  18 => "dezeoito"
  1  => "um"

In [66]:
numbers[1]

"um"

In [67]:
numbers[20]

"vinte"

In [68]:
typeof(numbers)

Dict{Int64, String}

In [69]:
numbers

Dict{Int64, String} with 4 entries:
  5  => "cinco"
  20 => "vinte"
  18 => "dezeoito"
  1  => "um"

In [70]:
delete!(numbers,1)

Dict{Int64, String} with 3 entries:
  5  => "cinco"
  20 => "vinte"
  18 => "dezeoito"

In [71]:
keys(numbers)

KeySet for a Dict{Int64, String} with 3 entries. Keys:
  5
  20
  18

In [72]:
values(numbers)

ValueIterator for a Dict{Int64, String} with 3 entries. Values:
  "cinco"
  "vinte"
  "dezeoito"

In [73]:
jedi = Dict("Anakin"=>"Dark",
    "Obi-Wan"=>"light",
    "Yoda"=>"light",
    "sidius"=>"dark"
    )

Dict{String, String} with 4 entries:
  "sidius"  => "dark"
  "Yoda"    => "light"
  "Anakin"  => "Dark"
  "Obi-Wan" => "light"

In [74]:
jedi["Anakin"]

"Dark"

Chaves e valores de um dicionário podem ser de qualquer tipo.

In [75]:
star_wars= 
Dict("movie_name"=> 
    Dict("A new hope"=> 
        Dict("year"=>1977,
            "director"=>"Geoge Luca",
            "Duration_minutes"=>121
            )        
        ),
    "Return of the Jedi"=>
        Dict("year"=>1977,
            "director"=>"Geoge Luca",
            "Duration_minutes"=>121
            ),        
    "general_description"=>"Adventures through the galaxy"
    )

Dict{String, Any} with 3 entries:
  "Return of the Jedi"  => Dict{String, Any}("director"=>"Geoge Luca", "year"=>…
  "general_description" => "Adventures through the galaxy"
  "movie_name"          => Dict{String, Dict{String, Any}}("A new hope"=>Dict("…

In [76]:
keys(star_wars)

KeySet for a Dict{String, Any} with 3 entries. Keys:
  "Return of the Jedi"
  "general_description"
  "movie_name"

In [77]:
keys(star_wars)

KeySet for a Dict{String, Any} with 3 entries. Keys:
  "Return of the Jedi"
  "general_description"
  "movie_name"

In [78]:
star_wars["Return of the Jedi"]["director"]

"Geoge Luca"

### Métodos em dicionários 

In [79]:
numbers = Dict(
    1=>"um", 
    5=>"cinco",
    18=>"dezeoito",
    20=>"vinte" )

Dict{Int64, String} with 4 entries:
  5  => "cinco"
  20 => "vinte"
  18 => "dezeoito"
  1  => "um"

In [80]:
delete!(numbers,1)

Dict{Int64, String} with 3 entries:
  5  => "cinco"
  20 => "vinte"
  18 => "dezeoito"

In [81]:
numbers

Dict{Int64, String} with 3 entries:
  5  => "cinco"
  20 => "vinte"
  18 => "dezeoito"

## Conjuntos
https://www.geeksforgeeks.org/sets-in-julia/

In [82]:
set1 = Set()

Set{Any}()

In [83]:
typeof(set1)

Set{Any}

In [84]:
set2 = Set([1,2,3,4,5])

Set{Int64} with 5 elements:
  5
  4
  2
  3
  1

In [85]:
set3 =Set([1,2,3,"dark","side"]) 

Set{Any} with 5 elements:
  2
  "side"
  "dark"
  3
  1

In [86]:
"dark" in set3

true

In [87]:
union(set1,set3) 

Set{Any} with 5 elements:
  2
  "side"
  "dark"
  3
  1

In [88]:
intersect!(set1,set3)

Set{Any}()

In [89]:
set4= Set([2,3,"light","side"]) 

Set{Any} with 4 elements:
  2
  "side"
  "light"
  3

In [90]:
intersect!(set4,set3)

Set{Any} with 3 elements:
  2
  "side"
  3

In [91]:
setdiff(set4,set2)

Set{Any} with 1 element:
  "side"

In [92]:
set3

Set{Any} with 5 elements:
  2
  "side"
  "dark"
  3
  1

In [93]:
delete!(set3,1)

Set{Any} with 4 elements:
  2
  "side"
  "dark"
  3

In [94]:
set4

Set{Any} with 3 elements:
  2
  "side"
  3

## Mudando o tipo de das variáveis 

In [95]:
x =  trunc(Int,1.2)

1

In [96]:
typeof(x)

Int64

In [97]:
typeof(1.2)

Float64

In [98]:
y  = floor(1.2)

1.0

## Built  in  Function 

In [99]:
println("Ola mundo")

Ola mundo


In [100]:
array = [1,7,1,4,5]

5-element Vector{Int64}:
 1
 7
 1
 4
 5

In [101]:
maximum(array)

7

In [102]:

# encontrando a chave de valor máximo em um dicionário
my_dict = Dict('a'=> 51, 'b'=> 31, 'c'=> 20)
values(my_dict)


ValueIterator for a Dict{Char, Int64} with 3 entries. Values:
  51
  20
  31

In [103]:
tupl = (2,3,2,5,7,8)

(2, 3, 2, 5, 7, 8)

In [104]:
maximum(tupl)

8

In [105]:
maximum(values(my_dict))

51

In [106]:
array

5-element Vector{Int64}:
 1
 7
 1
 4
 5

In [107]:
sort(array)

5-element Vector{Int64}:
 1
 1
 4
 5
 7

In [108]:
?parse

search: parse tryparse partialsortperm partialsortperm! pairs skipchars



```
parse(type, str; base)
```

Parse a string as a number. For `Integer` types, a base can be specified (the default is 10). For floating-point types, the string is parsed as a decimal floating-point number.  `Complex` types are parsed from decimal strings of the form `"R±Iim"` as a `Complex(R,I)` of the requested type; `"i"` or `"j"` can also be used instead of `"im"`, and `"R"` or `"Iim"` are also permitted. If the string does not contain a valid number, an error is raised.

!!! compat "Julia 1.1"
    `parse(Bool, str)` requires at least Julia 1.1.


# Examples

```jldoctest
julia> parse(Int, "1234")
1234

julia> parse(Int, "1234", base = 5)
194

julia> parse(Int, "afc", base = 16)
2812

julia> parse(Float64, "1.2e-3")
0.0012

julia> parse(Complex{Float64}, "3.2e-1 + 4.5im")
0.32 + 4.5im
```

---

```
parse(::Type{Platform}, triplet::AbstractString)
```

Parses a string platform triplet back into a `Platform` object.
